--- 
document:
  name: Developer documentation
  description: |
    The Data & Analytics Framework (DAF, in short) is an open source project
    developed in the context of the activities planned by the Italian Three-Year
    Plan for ICT in Public Administration 2017 - 2019, approved by the Italian
    Government in the 2017.
  tags:
    - daf
